version: '3'
services:

  myphpbox:
    build: ./php
    ports:
      - "80:80"
    environment:
      - DB_HOST=mydb
    depends_on:
     - mydb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mydb
    depends_on:
      - mydb

  mydb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=thisisroot
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: